demo3/app1/urls.py
from django.conf.urls import url
from . import views
from . import  feed
app_name='app1'
urlpatterns=[
    url(r'^single/(\d+)/$',views.single,name='single'),
    url(r'^index/$',views.index,name='index'),
    url(r'^single/(\d+)/$',views.single,name='single'),
    url(r'^selcategory/(\d+)$',views.selategory,name='selcategory'),
    url(r'^seltag/(\d+)/$',views.seltag,name='seltag'),
    url(r'^rss/$',feed.App1Feed(),name='rss'),
    url(r'^contact/$',views.contact,name='contact'),
    url(r'^addimg/$',views.addimg,name='addimg'),

]

demo3/app2/urls.py
from django.conf.urls import url
from . import views
app_name='app2'
urlpatterns=[
    url(r'^msg/(\d+)/$',views.Msg,name='msg'),
]

demo3/demo3/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import  url,include
urlpatterns = [
    path('admin/', admin.site.urls),
    url('app1/',include('app1.urls',namespace='app1')),
    url('app2/',include('app2.urls',namespace='app2')),
    url(r'^search/', include('haystack.urls')),
]

demo3/app1/models.py
from django.db import models
from django.contrib.auth.models import User
from tinymce.models import HTMLField
# Create your models here.


# 文章类别
class Category(models.Model):
    title=models.CharField(max_length=30,verbose_name='类别')
    class Meta():
        verbose_name = "类别"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title


# 文章标签
class Pags(models.Model):
    title=models.CharField(max_length=30,verbose_name='标签')
    class Meta():
        verbose_name = "标签"
        verbose_name_plural = verbose_name


    def __str__(self):
        return self.title


# 文章
class Articles(models.Model):
    title=models.CharField(max_length=30,verbose_name='标题')
    create_time=models.DateTimeField(auto_now_add=True,verbose_name='创建时间')
    update_time=models.DateTimeField(auto_now=True,verbose_name='修改时间')
    Readnum=models.PositiveIntegerField(default=0,verbose_name='阅读数')
    bodytxt=models.TextField(max_length=500,default='',verbose_name='正文')
    author=models.ForeignKey(User,on_delete=models.CASCADE,verbose_name='作者')
    category=models.ForeignKey(Category,on_delete=models.CASCADE,verbose_name='文章类别')
    pag=models.ManyToManyField(Pags,verbose_name='标签')
    class Meta():
        verbose_name = "文章"
        verbose_name_plural = verbose_name



    def __str__(self):
        return self.title


class Feedback(models.Model):
    username=models.CharField(max_length=20,verbose_name='用户名')
    emal=models.EmailField(blank=True,null=True,verbose_name='邮箱')
    subject=models.CharField(max_length=30,verbose_name='主题')
    txt=HTMLField()

    def __str__(self):
        return self.username

class absimg(models.Model):
    img=models.ImageField(upload_to='abs',verbose_name='图片文件')
    msg=models.CharField(max_length=20,verbose_name='消息')
    class Meta():
        verbose_name = "轮播"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.msg

demo3/app2/models.py
from django.db import models
from app1.models import Articles
# Create your models here.

class Comment(models.Model):
    username=models.CharField(max_length=30,verbose_name='用户名')
    email=models.EmailField(blank=True,null=True,verbose_name='邮箱')
    url=models.URLField(blank=True,null=True,verbose_name='个人主页')
    tex=models.TextField(max_length=150,verbose_name='评论内容')
    title=models.ForeignKey(Articles,on_delete=models.CASCADE)
    creat_time=models.DateTimeField(auto_now_add=True,verbose_name='发布日期')

    def __str__(self):
        return self.username

demo3/app1/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from .models import Articles,Category,Pags,Feedback,absimg
from django.core.paginator import Paginator
from app2.models import Comment
from django.shortcuts import render,redirect,reverse
# Create your views here.
import markdown


from django.core.mail import send_mail,send_mass_mail
from django.conf import settings






def index(request):
    num=request.GET.get('page')
    print(num)
    if num== None:
        num=1
    articles=Articles.objects.all().order_by('-create_time')
    paginator=Paginator(articles,2)
    page=paginator.get_page(num)
    return render(request,'index.html',{'page':page})

def single(request,id):
    article = Articles.objects.get(pk=id)
    Messiges=article.comment_set.all()
    article.Readnum += 1
    article.save()
    if request.method=='GET':
        # article.bodytxt=markdown.markdown(article.bodytxt,extensions=[
        #     "markdown.extensions.extra",
        #     "markdown.extensions.codehilite",
        #     "markdown.extensions.toc"
        # ])
        mk=markdown.Markdown(extensions=[
            "markdown.extensions.extra",
            "markdown.extensions.codehilite",
            "markdown.extensions.toc"
        ])
        article.bodytxt=mk.convert(article.bodytxt)

        article.toc=mk.toc

        print(article.bodytxt)

        return render(request,'single.html',locals())


        # return redirect(reverse('app1:single'))


def selategory(request,id):
    articles=Category.objects.get(pk=id).articles_set.all()
    paginator = Paginator(articles, 2)
    page = paginator.get_page(1)
    return render(request, 'index.html', {'page': page})
    # return HttpResponse('分类查询')

def seltag(request,id):

    articles = Pags.objects.get(pk=id).articles_set.all()
    paginator = Paginator(articles, 2)
    page = paginator.get_page(1)
    return render(request, 'index.html', {'page': page})
    # return HttpResponse('标签查询')

def contact(request):
    if request.method=='GET':
        return render(request,'contact.html')
    elif request.method=='POST':
        try:
            feedbook = Feedback()
            feedbook.username = request.POST.get('name')
            feedbook.emal = request.POST.get('email')
            feedbook.subject = request.POST.get('subject')
            feedbook.txt = request.POST.get('message')
            # feedbook.save()   settings.DEFAULT_FROM_EMAIL
            send_mail(str(request.POST.get('subject')),request.POST.get('message'),settings.DEFAULT_FROM_EMAIL,['1103971604@qq.com'])
            print('发送成功')
            return redirect(reverse('app1:contact'))
        except Exception as e:
            print('发送失败')
            return redirect(reverse('app1:contact'))

    else:
        return HttpResponse('错误')


def addimg(request):
    if request.method=='GET':
        return render(request,'addimg.html')
    else:
        a=absimg()
        a.img=request.FILES.get('img')
        a.msg=request.POST.get('msg')
        a.save()
        return redirect(reverse('app1:index'))

demo3/app2/views.py
from django.shortcuts import render,redirect,reverse
from .models import Comment
from app1.models import Articles
from django.http import HttpResponseRedirect,HttpResponse
# Create your views here.

def Msg(request,id):

    if request.method=='POST':
        article = Articles.objects.get(pk=id)
        name = request.POST.get('name')
        email = request.POST.get('email')
        url = request.POST.get('url')
        comment = request.POST.get('comment')
        Messige = Comment()
        Messige.username = name
        Messige.email = email
        Messige.url = url
        Messige.tex = comment
        Messige.title = article
        Messige.save()
        # return HttpResponseRedirect('/app1/single/%s/'%(id,))
        return redirect(reverse('app1:single',args=(id,)))

demo3/templates/about.html
<!DOCTYPE html>
<html>
	<head>
		<title>Black &amp; White</title>

		<!-- meta -->
		<meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">

	    <!-- css -->
		<link rel="stylesheet" href="css/bootstrap.min.css">
		<link rel="stylesheet" href="css/ionicons.min.css">
		<link rel="stylesheet" href="css/pace.css">
	    <link rel="stylesheet" href="css/custom.css">

	    <!-- js -->
	    <script src="js/jquery-2.1.3.min.js"></script>
	    <script src="js/bootstrap.min.js"></script>
	    <script src="js/pace.min.js"></script>
	    <script src="js/modernizr.custom.js"></script>
	</head>

	<body id="page">
		<div class="container">	
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
							<h1><a href="index.html"><b>Black</b> &amp; White</a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href="index.html" data-hover="Home">Home</a></li>
    								<li class="cl-effect-11"><a href="full-width.html" data-hover="Blog">Blog</a></li>
    								<li class="cl-effect-11"><a href="about.html" data-hover="About">About</a></li>
    								<li class="cl-effect-11"><a href="contact.html" data-hover="Contact">Contact</a></li>
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="#">
									<input type="search" placeholder="Search" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>				
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">About Me</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<figure class="img-responsive-center">
									<img class="img-responsive" src="img/me.jpg" alt="Developer Image">
								</figure>
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<div class="height-40px"></div>
								<h2 class="title text-center">Social</h2>
								<ul class="social">
									<li class="facebook"><a href="#"><span class="ion-social-facebook"></span></a></li>
									<li class="twitter"><a href="#"><span class="ion-social-twitter"></span></a></li>
									<li class="google-plus"><a href="#"><span class="ion-social-googleplus"></span></a></li>
									<li class="tumblr"><a href="#"><span class="ion-social-tumblr"></span></a></li>
								</ul>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2014 ThemeWagon.com</p>
					</div>
				</div>
			</div>
		</footer>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="index.html">Home</a></li>
					<li><a href="full-width.html">Blog</a></li>
					<li><a href="about.html">About</a></li>
					<li><a href="contact.html">Contact</a></li>
				</ul>
			</nav>
		</div>

		<script src="js/script.js"></script>
		
	</body>
</html>

demo3/templates/addimg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>addimg</title>
</head>
<body>

<form action="{% url 'app1:addimg' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    图片: <input type="file" name="img">
    说明: <input type="text" name="msg">
    <input type="submit" value="提交">


</form>




</body>
</html>

demo3/templates/base.html
{% load func1 %}

<!DOCTYPE html>
<html lang="en">
<head>

    <title>  {% block title %} {% endblock %} </title>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="/static/css/pace.css">
    <link rel="stylesheet" href="/static/css/custom.css">

    <!-- js -->
    <script src="/static/js/jquery-2.1.3.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/pace.min.js"></script>
    <script src="/static/js/modernizr.custom.js"></script>

</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'app1:index' %}"><b>Black</b> &amp; White</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'app1:index' %}" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="full-width.html" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="about.html" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="{% url 'app1:contact' %}" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="/search/">
                            <input type="search" placeholder="搜索" required name="q">
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>
<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>
<div class="copyrights">Modified by <a href="http://zmrenwu.com/">追梦人物的博客</a></div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">

                {% block left %}

                {% endblock %}

            </main>
            <aside class="col-md-4">
                {% block catalog %}
                {% endblock %}
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    <ul>

                        {% getnewcomments 3 as newcomment %}

                        {% for i in newcomment %}
                            <li><a href="{% url 'app1:single' i.id %}">{{i.title}}</a></li>
                        {% endfor %}

                    </ul>
                </div>
                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    <ul>
                        <li>
                            <a href="#">2017 年 5 月</a>
                        </li>
                        <li>
                            <a href="#">2017 年 4 月</a>
                        </li>
                        <li>
                            <a href="#">2017 年 3 月</a>
                        </li>
                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    <ul>

                        {% getcategorys as category %}

                        {% for i in category %}
                            <li><a href="{% url 'app1:selcategory' i.id %}">{{i.title}} ({{ i.articles_set.count }})</a></li>
                        {% endfor %}


                    </ul>

                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    <ul>
                        {% gettags as tags %}
                        {%for i in tags %}
                        <li><a href="{% url 'app1:seltag' i.id %}">{{i.title}}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="rss">
                    <a href="{% url 'app1:rss'  %}"><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2017 - 采集自<a href="http://www.cssmoban.com/"
                                                        target="_blank" title="模板之家">模板之家</a>
                    - 由<a href="http://zmrenwu.com/" title="网页模板" target="_blank">追梦人物的博客</a>修改
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="index.html">首页</a></li>
            <li><a href="full-width.html">博客</a></li>
            <li><a href="about.html">关于</a></li>
            <li><a href="contact.html">联系</a></li>
        </ul>
    </nav>
</div>

<script src="/static/js/script.js"></script>


</body>
</html>

demo3/templates/base2.html
<!DOCTYPE html>
<html lang="en">
<html lang="en">
<head>

    <title>  {% block title %} {% endblock %} </title>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="/static/css/pace.css">
    <link rel="stylesheet" href="/static/css/custom.css">

    <!-- js -->
    <script src="/static/js/jquery-2.1.3.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/pace.min.js"></script>
    <script src="/static/js/modernizr.custom.js"></script>

</head>
<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'app1:index' %}"><b>Black</b> &amp; White</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'app1:index' %}" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="full-width.html" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="about.html" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="contact.html" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="#">
                            <input type="search" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>
<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>
<div class="copyrights">Modified by <a href="http://zmrenwu.com/">追梦人物的博客</a></div>





{% block cent%}

{% endblock %}

<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2017 - 采集自<a href="http://www.cssmoban.com/"
                                                        target="_blank" title="模板之家">模板之家</a>
                    - 由<a href="http://zmrenwu.com/" title="网页模板" target="_blank">追梦人物的博客</a>修改
                </p>
            </div>
        </div>
    </div>
</footer>



<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="index.html">首页</a></li>
            <li><a href="full-width.html">博客</a></li>
            <li><a href="about.html">关于</a></li>
            <li><a href="contact.html">联系</a></li>
        </ul>
    </nav>
</div>

<script src="/static/js/script.js"></script>
</body>
</html>

demo3/templates/contact.html
<script src="/static/tiny_mce/tiny_mce.js"></script>
<script type="text/javascript">
	tinyMCE.init({
	  'mode':'textareas',
	  'theme':'advanced',
	  'width': '100%' ,
	  'height':100
	});
</script>


{% extends 'base2.html' %}
{% block cent%}


<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">Contact</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<form action="{% url 'app1:contact' %}" method="post" class="contact-form">
									{% csrf_token %}
									<div class="row">
										<div class="col-md-6 col-md-offset-3">
											<input type="text" name="name" placeholder="用户名1" required>
											<input type="email" name="email" placeholder="邮箱1" required>
											<input type="text" name="subject" placeholder="Subject1" required>
											<textarea name="message" rows="7" placeholder="您的建议" required > </textarea>
											<input type="submit" value="提交">
										</div>
									</div>	<!-- row -->

								</form>

							</div>
						</article>
					</main>
				</div>
			</div>
		</div>

{% endblock %}





		

demo3/templates/index.html
{% extends 'base.html' %}
{% load func1 %}

{% block title %} 主页 {% endblock %}

{% block left %}

    <a href="{% url 'app1:addimg' %}">添加图片</a>


    {% getimgs as imgs %}

<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">

      {% for img in imgs %}
        {% if img == imgs.first %}
            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        {% else %}
            <li data-target="#carousel-example-generic" data-slide-to="{{ forloop.counter|add:-1 }}"></li>
        {% endif %}
      {% endfor %}
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
      {% for img in imgs %}
        {% if img == imgs.first %}
            <div class="item active">
          <img src="/static/media/{{img.img}}" alt="...">
          <div class="carousel-caption">
            {{img.msg}}
          </div>
    </div>
        {% else %}
            <div class="item">
          <img src="/static/media/{{img.img}}" alt="...">
          <div class="carousel-caption">
            {{img.msg}}
          </div>
    </div>
        {% endif %}
      {% endfor %}

  </div>


  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

    {% for article in page.object_list %}
        <article class="post post-1">
        <header class="entry-header">
            <h1 class="entry-title">
                <a href="{% url 'app1:single' article.id %}">{{article.title}}</a>
            </h1>
            <div class="entry-meta">
                <span class="post-category"><a href="#">{{article.title}}</a></span>
                <span class="post-date"><a href="#"><time class="entry-date"
                                                          datetime="2012-11-09T23:15:57+00:00">{{article.create_time}}</time></a></span>
                <span class="post-author"><a href="#">{{article.author}}</a></span>
                <span class="comments-link"><a href="#">{{article.comment_set.count}} 评论</a></span>
                <span class="views-count"><a href="#">{{article.Readnum}} 阅读</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            <p>{{article.bodytxt|txtlen:80}}...</p>
            <div class="read-more cl-effect-14">
                <a href="#" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
            </div>
        </div>
    </article>
    {% empty %}
        没有文章
    {% endfor %}

    <div class="pagination">



    <ul>
        {% if page.has_previous %}
        <li><a href="?page={{page.previous_page_number}}">上一页</a></li>
        {% endif %}

        {% for num in page.paginator.page_range %}
            <li><a href="?page={{num}}">{{num}}</a></li>
        {% endfor %}

        {% if page.has_next %}
            <li><a href="?page={{page.next_page_number}}">下一页</a></li>
        {% endif %}

    </ul>


</div>
{% endblock %}

demo3/templates/search/search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>搜索结果</title>
</head>
<body>
    搜索内容:{{query}}

    {% if query %}
        {% for i in page.object_list %}
            <li><a href="{% url 'app1:single' i.object.id %}">{{i.object.title}}</a></li>
        {% empty %}
            <li>没有内容</li>
        {% endfor %}

    {% endif %}


</body>
</html>

demo3/templates/single.html
{% extends 'base.html' %}
{% block title %} 详情 {% endblock %}

{% block left %}
    <article class="post post-1">
                    <header class="entry-header">
                        <h1 class="entry-title">{{article.title}}</h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#">{{article.title}}</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="2012-11-09T23:15:57+00:00">{{article.create_time}}</time></a></span>
                            <span class="post-author"><a href="#">{{article.author}}</a></span>
                            <span class="comments-link"><a href="#">{{article.comment_set.count}} 评论</a></span>
                            <span class="views-count"><a href="#">{{article.Readnum}} 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        {{article.bodytxt|safe}}
                    </div>
                </article>
                <section class="comment-area" id="comment-area">
                    <hr>
                    <h3>发表评论</h3>
                    <form action="{% url 'app2:msg' article.id  %}" method="post" class="comment-form">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-4">
                                <label for="id_name">名字：</label>
                                <input type="text" id="id_name" name="name" required>
                            </div>
                            <div class="col-md-4">
                                <label for="id_email">邮箱：</label>
                                <input type="email" id="id_email" name="email" required>
                            </div>
                            <div class="col-md-4">
                                <label for="id_url">网址：</label>
                                <input type="text" id="id_url" name="url">
                            </div>
                            <div class="col-md-12">
                                <label for="id_comment">评论：</label>
                                <textarea name="comment" id="id_comment" required></textarea>
                                <button type="submit" class="comment-btn">发表</button>
                            </div>
                        </div>    <!-- row -->
                    </form>
                    <div class="comment-list-panel">

                        <h3>评论列表，共 <span>{{Messiges.count}}</span> 条评论</h3>
                        <ul class="comment-list list-unstyled">

                            {% for i in Messiges %}
                            <li class="comment-item">
                                <span class="nickname">{{i.username}}</span>
                                <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">{{i.creat_time}}</time>
                                <div class="text">
                                    {{i.tex}}
                                </div>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </section>


{% endblock %}

{% block catalog %}
<div class="widget widget-content">
                    <h3 class="widget-title">文章目录</h3>
                    {{article.toc|safe}}
                </div>
{% endblock %}