test1/book/urls.py
from django.conf.urls import url
from . import views

app_name='booktest'

urlpatterns = [
    url(r'^list/$',views.list,name='list'),
    url(r'^detil/(\d+)/$',views.detil,name='detil'),
    url(r'^index/$',views.index,name='index'),
    url(r'^delbook/(\d+)/$',views.delbook,name='delbook'),
    url(r'^deldetil/(\d+)/$',views.deldetil,name='deldetil'),
    url(r'^addbook/$',views.addbook,name='addbook'),
    url(r'^adddetil/(\d+)/$',views.adddetil,name='adddetil'),
    url(r'^setbook/(\d+)$',views.setbook,name='setbook'),
    url(r'^setdetil/(\d+)/$',views.setdetil,name='setdetil'),


]

test1/test1/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from django.http import HttpResponse
from django.shortcuts import render

def mainindex(request):
    return render(request,'test1/index.html')


urlpatterns = [
    path('admin/', admin.site.urls),
    url('book/',include('book.urls',namespace='booktest')),
    # namespace 解除硬编码 作用
    url('vote/',include('vote.urls',namespace='votetest')),
    url('index/',mainindex,name='index'),
]

test1/book/models.py
from django.db import models

# Create your models here.

class bookinfo(models.Model):
    title=models.CharField(max_length=30,verbose_name='书名')
    bpub_date=models.DateTimeField(auto_now_add=True,verbose_name='发布日期')

    def __str__(self):
        return self.title

class heroinfo(models.Model):
    heroname=models.CharField(max_length=30,verbose_name='姓名')
    heroage=models.IntegerField(verbose_name='年龄')
    # hgender=models.BooleanField(default=True)
    hgender=models.CharField(max_length=10,choices=(('1','男'),('2','女')),verbose_name='性别')
    nbook=models.ForeignKey(bookinfo,on_delete=models.CASCADE,verbose_name='所属丛书')

    def __str__(self):
        return self.heroname




class createuser(models.Manager):
    def newuser(self,name):
        a=self.model()
        a.username=name
        a.save()


class user(models.Model):
    username=models.CharField(max_length=20)

    c=createuser()

    @classmethod
    def creat(cls,name):
        a=cls(username=name)
        a.save()
    @classmethod
    def show(cls,name):
        print(cls)  #返回是一个 类
        return cls.c.get(username=name)

test1/book/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from django.template import loader
from .models import bookinfo,heroinfo
# Create your views here.

def index(request):
    # return HttpResponse('index')

    temp=loader.get_template('book/index.html')
    context={}
    resul=temp.render(context)
    return HttpResponse(resul)


def list(request):
    temp=loader.get_template('book/list.html')
    books=bookinfo.objects.all()
    restul=temp.render({'books':books})
    return HttpResponse(restul)

def detil(request,id):
    temp=loader.get_template('book/detil.html')
    book=bookinfo.objects.get(id=id)
    restul=temp.render({'book':book})
    return HttpResponse(restul)


def delbook(request,id):
    print(id)
    # return HttpResponse('成功')
    bookinfo.objects.get(pk=id).delete()
    return HttpResponseRedirect('/book/list/')

def deldetil(request,id):
    print(id)
    # return HttpResponse('成功')
    hero=heroinfo.objects.get(pk=id)
    a=hero.nbook.id
    hero.delete()
    return HttpResponseRedirect('/book/detil/%s/'%(a,))

def addbook(request):
    if request.method=='GET':
        return render(request,'book/addbook.html')
    elif request.method=='POST':
        bookname=request.POST['bookname']
        b1=bookinfo()
        b1.title=bookname
        b1.save()
        return HttpResponseRedirect('/book/list/')

def adddetil(request,bookid):
    if request.method=='GET':
        return render(request,'book/addhero.html', {'bookid':bookid})
    elif request.method=='POST':
        book=bookinfo.objects.get(pk=bookid)
        h1=heroinfo()
        h1.heroname=request.POST['name']
        h1.heroage = request.POST['age']
        h1.hgender = request.POST['sex']
        h1.nbook=book
        h1.save()
        return HttpResponseRedirect('/book/detil/%s/'%(bookid,))

def setbook(request,id):
    if request.method=='GET':
        return render(request,'book/setbook.html' ,{'bookid':id })
    if request.method=='POST':
        book=bookinfo.objects.get(pk=id)
        book.title=request.POST['newname']
        book.save()
        return HttpResponseRedirect('/book/list/')


def setdetil(request,id):
    if request.method=='GET':
        return render(request,'book/setdetil.html',{'heroid':id})
    elif request.method=='POST':
        h1=heroinfo.objects.get(pk=id)
        bookid=h1.nbook.id
        h1.heroname = request.POST['name']
        h1.heroage = request.POST['age']
        h1.hgender = request.POST['sex']
        h1.save()
        return HttpResponseRedirect('/book/detil/%s/' % (bookid,))

test1/templates/book/addbook.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加书</title>
</head>
<body>
    <h1>添加一本书</h1>
    <form action="{% url 'booktest:addbook' %}" method="post">
        书名: <input type="text" name="bookname">
        <input type="submit" value="提交">




    </form>
</body>
</html>

test1/templates/book/addhero.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加英雄</title>
</head>
<body>
    <h1>添加英雄</h1>
    <form action="{% url 'booktest:adddetil' bookid %}" method="post">
        角色名字: <input type="text" name="name">
        年龄: <input type="number" name="age" min="0">
        性别: <input type="radio" name="sex" value="1" checked>男
            <input type="radio" name="sex" value="2">女
        <input type="submit" value="提交">
    </form>

</body>
</html>

test1/templates/book/detil.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>详情页</title>
</head>
<body>
    <h1>书籍英雄</h1>

    {% if book %}
        {{ book.title }}
        <ul>
            {% for hero in book.heroinfo_set.all %}
                <li>{{ hero.heroname }} <a href="{% url 'booktest:deldetil' hero.id %}">删除</a>
                    <a href="{% url 'booktest:setdetil' hero.id %}">修改</a>


                </li>
            {% empty %}
                英雄为空
            {% endfor %}
        </ul>
    {% else %}
        没有英雄
    {% endif %}
    <br>
    <a href="{% url 'booktest:adddetil' book.id %}">添加一个角色</a>
    <br>
    <a href="{% url 'booktest:list' %}">返回列表</a>
    <br>
    <a href="{% url 'booktest:index' %}">返回首页</a>

</body>
</html>

test1/templates/book/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>


    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
     <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
    <div class="contaior" >
        <h1>首页</h1>
        <a href="{% url 'booktest:list' %}">列表页</a>

    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
      </ol>

      <!-- Wrapper for slides -->
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img src="/static/img/bookimg/hot1.jpg" alt="...">
          <div class="carousel-caption">
            第一张轮播图
          </div>
        </div>
        <div class="item">
          <img src="/static/img/bookimg/hot1.jpg" alt="...">
          <div class="carousel-caption">
            第二章轮播图
          </div>
        </div>
           <div class="item">
          <img src="/static/img/bookimg/hot1.jpg" alt="...">
          <div class="carousel-caption">
            第三章轮播图
          </div>
        </div>
        ...
      </div>
      <!-- Controls -->
      <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>




    </div>
</body>
</html>

test1/templates/book/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>列表</title>
</head>
<body>
    <h1>列表页</h1>

    {% if books %}
        {% for book in books %}
        <li><a href="{% url 'booktest:detil' book.id %}">{{ book.title }}</a> <a href="{% url 'booktest:delbook' book.id %}">删除</a>
            <a href="{% url 'booktest:setbook' book.id %}">修改</a>

        </li>
        {% empty %}
            没有书籍信息
        {% endfor %}
    {% else %}
        没有书
    {% endif %}

    <br>
    <a href="{% url 'booktest:addbook' %}">添加一本书</a>
    <a href="{% url 'booktest:index' %}">返回首页</a>
</body>
</html>

test1/templates/book/setbook.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>修改书名</title>
</head>
<body>
    <h1>修改书名</h1>

    <form action="{% url 'booktest:setbook' bookid %}" method="post">
        书名: <input type="text" name="newname" >
        <input type="submit" value="提交">




    </form>



</body>
</html>

test1/templates/book/setdetil.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>修改角色信息</title>
</head>
<body>
    <h1>修改角色信息</h1>
    <form action="{% url 'booktest:setdetil' heroid  %}" method="post">
        角色名字: <input type="text" name="name" >
        年龄: <input type="number" name="age" min="0">
        性别: <input type="radio" name="sex" value="1" checked>男
            <input type="radio" name="sex" value="2">女
        <input type="submit" value="提交">
    </form>


</body>
</html>